<a href="https://colab.research.google.com/github/ArturPalys/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



*   @author: artur.palys@gmail.com (na bazie kursu który POLECAM - Data Science: Kompletny Bootcamp w języku Python - autorstwa Paweł Krakowiak)
*   @site:



### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)

>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)

>Podstawowa biblioteka do obliczeń numerycznych w języku Python

```
pip install numpy
```

### Spis treści:


1.   [Podstawy](#s1)
2.   [Typy danych](#s2)
3.   [Tworzenie tablic](#s3)
4.   [Podstawowe operacje na tablicach](#s4)
5.   [Generowanie liczb pseudolosowych](#s5)
6.   [Podstawowe funkcje](#s6)
7.   [Indeksowanie i wycinanie](#s7)
8.   [Iteracja po tablicach](#s8)
9.   [Zmiana rozmiaru tablic](#s9)
10.  [Maski logiczne](#s10)

### <a name='s1'></a> Podstawy

In [2]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

wymiar tablicy

In [ ]:
x.ndim

1

kształt - długość odpowiedniego wymiaru tablicy (tupla/krotka)


In [ ]:
x.shape

(2,)

In [ ]:
help(np.shape)

In [ ]:
x.size

2

typ danych

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.shape

(3,)

In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [4]:
x = np.array([[1, 2, 3], [4, 2, 1]])
x

array([[1, 2, 3],
       [4, 2, 1]])

2 wiersze 3 kolumny (2 wymiary-macierz)

In [5]:
x.shape

(2, 3)

In [6]:
x.size

6

3D Array (np obraz)

In [ ]:
x = np.array(

             [[[4, 3, 2],
               [3, 1, 2]],

              [[4, 1, 3],
               [4, 2, 1]]]
)
x

array([[[4, 3, 2],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

2 tabele/elementy, 2 wiersze, 3 kolumny  (3 wymiary)

In [ ]:
x.shape

(2, 2, 3)

### <a name='s2'></a>Typy danych

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.1, 3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A

array([1., 2., 3.])

liczby złożone (zespolone)

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([1.0, 2.1, 3.3], dtype='int')
A.dtype

dtype('int64')

obcięte liczby z float do int

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

wbudowane typy np dla piksela - zajmują mniej miejsca int8

In [ ]:
A = np.array([24, 12, 23], dtype=np.int8)
A.dtype

dtype('int8')

najlepiej wartości poksela od 0..255 uint8

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

### <a name='s3'></a> Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
X = np.zeros(shape=(3, 2, 4, 10))
X

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0

In [8]:
X.size

240

In [9]:
X.ndim

4

In [10]:
X.shape

(3, 2, 4, 10)

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step= 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step= -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

równo rozłożony przedział od start do stop w liczbie=num elementami

In [ ]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

reshape(3, -1) -> 3 wiersze ile tam kolumn wyjdzie

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

reshape(-1, 3) -> 3 kolumny i ile tam wierszy wyjdzie

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='s4'></a> Podstawowe operacje na tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)


[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
B - A


array([ 0, -2, -1,  0])

In [ ]:
np.subtract(B, A)

array([ 0, -2, -1,  0])

In [ ]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
A + 3 * B

array([12, -2, 13,  8])

Mnożenie zwykłe

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X * Y

array([[6, 0],
       [2, 0]])

Mnożenie macierzy

In [ ]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y @ X

array([[ 6, 18],
       [-5, -3]])

### <a name='s5'></a> Generowanie liczb pseudolosowych

In [3]:
np.random.seed(0)

standardowy rozkład normalny

In [4]:
np.random.randn()

1.764052345967664

In [ ]:
help(np.random.randn)

In [5]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [6]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

rozkład jednostajny na przedziale <0, 1)

In [7]:
np.random.rand()

0.1965823616800535

In [12]:
np.random.rand(10)

array([0.09710128, 0.83794491, 0.09609841, 0.97645947, 0.4686512 ,
       0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696])

In [13]:
np.random.rand(10, 2)

array([[0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609],
       [0.18319136, 0.58651293]])

losowa liczba <0, 10)

In [16]:
np.random.randint(10)

8

Losowa liczba dwucyfrowa <10, 101)

In [17]:
np.random.randint(low=10, high=101)

12

In [19]:
np.random.randint(low=10, high=101, size=10)

array([13, 23, 50, 82, 29, 82, 36, 76, 62, 77])

losowy element z listy

In [21]:
np.random.choice([4, 2, 1, 3])

4

In [22]:
np.random.choice(['a', 'b', 'c', 'd'])

'b'

In [24]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

przetasuj

In [33]:
np.random.shuffle(data)
data

array([5, 1, 0, 8, 2, 7, 6, 9, 3, 4])

### <a name='s6'></a> Podstawowe funkcje

exponent


In [34]:
np.exp(1)

2.718281828459045

In [35]:
np.sqrt(9)

3.0

In [36]:
np.all([2, 3, 1])

True

In [37]:
np.all([2, 3, 1, 0])

False

In [38]:
np.any([1, 0, 0])

True

In [39]:
np.any([0, 0, 0])

False

In [40]:
bool(0)

False

In [41]:
bool(2.3)

True

In [44]:
A = np.random.rand(5)
A

array([0.34535168, 0.92808129, 0.7044144 , 0.03183893, 0.16469416])

indeks wartości największej

In [45]:
np.argmax(A)

1

In [46]:
A[np.argmax(A)]

0.9280812934655909

In [47]:
np.argmin(A)

3

In [48]:
A[np.argmin(A)]

0.03183892953130785

sortowanie od wartości najmniejszej do najwieszej - podaje indeksy

In [49]:
np.argsort(A)

array([3, 4, 0, 2, 1])

In [50]:
np.max(A)

0.9280812934655909

In [51]:
np.min(A)

0.03183892953130785

średnia

In [52]:
np.mean(A)

0.43487609242304937

mediana

In [53]:
np.median(A)

0.3453516806969027

odchylenie standardowe

In [54]:
np.std(A)

0.3344709625934017

### <a name='s7'></a> Indeksowanie i wycinanie

In [55]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
# A[idx], A[start:stop], A[:stop], A[start:]
print(A[0])
print(A[0:3])
print(A[:5])
print(A[6:])

0
[0 1 2]
[0 1 2 3 4]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [68]:
A[[0, 19, 4]]

array([ 0, 19,  4])

In [69]:
A[-1]

19

In [70]:
A[-2]

18

wycinanie z tablicy dwuwymiarowej - wiersze

In [73]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
A[0]

array([0, 1, 2, 3, 4])

In [75]:
A[1]

array([5, 6, 7, 8, 9])

wycinanie z tablicy dwuwymiarowej - kolumny

In [78]:
A[:, 0]

array([ 0,  5, 10, 15])

In [80]:
A[:, 1]

array([ 1,  6, 11, 16])

ostatnia kolumna

In [82]:
A[:, -1]

array([ 4,  9, 14, 19])

In [81]:
A[:, :]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

konkretny element macierzy - podajemy indeks wiersza i kolumny

In [83]:
A[1, 1]

6

fragment macierzy

In [84]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [86]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='s7'></a> Iteracja po tablicach

In [87]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [88]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [89]:
for row in A:
  print(row[0])

0
5
10
15


In [90]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


iteracja po każdym elemencie tablicy - wypłaszczenie flat

In [91]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='s9'></a> Zmiana rozmiaru tablic

In [92]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [93]:
A.shape

(4, 5)

In [94]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

wypłaszczenie na jeden wymiar

In [95]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

transponowanie macierzy - zamiana kolumn na wiersze

In [97]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='s10'></a> Maski logiczne

In [114]:
A = np.arange(start=-10, stop=10, step=0.5)
print(A)
A = A.reshape(10, -1)
A

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5]


array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

sprawdzamy gdzie mamy wartości dodatnie

In [115]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [116]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [117]:
A<0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [118]:
A[A<0]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5])

In [119]:
A==0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [120]:
A[A==0]

array([0.])

In [122]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [123]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [124]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [126]:
A[np.bitwise_or(A<-5, A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])