<a href="https://colab.research.google.com/github/ArturPalys/data-science-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



*   @author: artur.palys@gmail.com (na bazie kursu który POLECAM - Data Science: Kompletny Bootcamp w języku Python - autorstwa Paweł Krakowiak)
*   @site:



### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)

>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)

>Podstawowa biblioteka do obliczeń numerycznych w języku Python

```
pip install numpy
```


### Funkcje statystyczne

In [1]:
import numpy as np
np.__version__

'1.25.2'

In [2]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum() - wszystkie wartości z macierzy

In [3]:
price.sum()

4650.1

In [6]:
np.sum(price)

4650.1

sumowane kolumny

In [4]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [7]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

sumowanie po wierszach

In [5]:
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [8]:
np.sum(price, axis=1)

array([1049.7, 2049.4, 1551. ])

min()

In [9]:
np.min(price)

11.7

In [13]:
print(price, '\n')
print(np.min(price, axis=0))

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]] 

[  12.2   12.8   11.7   12.2 1000. ]


In [14]:
print(np.min(price, axis=1))

[11.9 11.7 12.2]


median()

Mediana to miara statystyczna, która wskazuje na wartość środkową w uporządkowanym szeregu danych1234. W przypadku nieparzystej liczby elementów w szeregu, mediana to wartość środkowa. Jeżeli natomiast liczba elementów jest parzysta, mediana jest równa średniej arytmetycznej dwóch środkowych liczb2.

Na przykład, dla zbioru liczb: 2, 4, 4, 4, 5, 5, 5, 5, mediana wynosi 4 i pół1. Dla zbioru: 2, 3, 4, 7, 8, 9, mediana jest równa 11/22.

Mediana jest mniej podatna na “dziwne rzeczy” - rzadkie, odstające wartości, co czyni ją bardziej “sprawiedliwą” miarą centralną, szczególnie w przypadku danych z dużymi odchyleniami lub skośnością1.

In [15]:
np.median(price)

12.6

mean() - średnia arytmetyczna

In [16]:
np.mean(price)

310.0066666666667

In [20]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

std() - odchylenie standardowe/wymiary rozrzutu

Odchylenie standardowe to miara statystyczna, która pokazuje, jak bardzo wartości w zestawie danych różnią się od średniej arytmetycznej tych danych1. Jest to miara rozproszenia wyników średniej arytmetycznej2.

Intuicyjnie rzecz ujmując, odchylenie standardowe mówi, jak szeroko wartości jakiejś wielkości (na przykład wieku, inflacji, kursu walutowego) są rozrzucone wokół jej średniej3. Im mniejsza wartość odchylenia tym obserwacje są bardziej skupione wokół średniej3.

In [21]:
np.std(price)

622.3781502877133

In [22]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

var() - wariancja

Wariancja to miara statystyczna, która informuje o stopniu zróżnicowania wyników w danym zbiorze danych1. Jest to średnia arytmetyczna kwadratów różnic pomiędzy wynikiem danej obserwacji a średnią dla danej grupy12.

Wariancja jest podstawową miarą zmienności obserwowanych wyników1. Jeżeli wariancja wynosi 0, to oznacza, że wszystkie wyniki są identyczne1.

In [23]:
np.var(price)

387354.5619555555

In [24]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])