<a href="https://colab.research.google.com/github/ArturPalys/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



*   @author: artur.palys@gmail.com
*   @site:



### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)

>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)

>Podstawowa biblioteka do obliczeń numerycznych w języku Python

```
pip install numpy
```

### Spis treści:


1.   [Podstawy](#s1)
2.   [Typy danych](#s2)
3.   [Tworzenie tablic](#s3)



### <a name='s1'></a> Podstawy

In [1]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

wymiar tablicy

In [7]:
x.ndim

1

kształt - długość odpowiedniego wymiaru tablicy (tupla/krotka)


In [8]:
x.shape

(2,)

In [ ]:
help(np.shape)

In [10]:
x.size

2

typ danych

In [11]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [13]:
x.shape

(3,)

In [14]:
x.dtype

dtype('float64')

2D Array

In [15]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [16]:
x.ndim

2

In [17]:
x.shape

(2, 2)

In [18]:
x = np.array([[1, 2, 3], [4, 2, 1]])
x

array([[1, 2, 3],
       [4, 2, 1]])

2 wiersze 3 kolumny (2 wymiary-macierz)

In [19]:
x.shape

(2, 3)

3D Array (np obraz)

In [20]:
x = np.array(

             [[[4, 3, 2],
               [3, 1, 2]],

              [[4, 1, 3],
               [4, 2, 1]]]
)
x

array([[[4, 3, 2],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [21]:
x.ndim

3

2 tabele/elementy, 2 wiersze, 3 kolumny  (3 wymiary)

In [22]:
x.shape

(2, 2, 3)

### <a name='s2'></a>Typy danych

In [23]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [24]:
A = np.array([1.0, 2.1, 3.3])
A.dtype

dtype('float64')

In [25]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [26]:
A

array([1., 2., 3.])

liczby złożone (zespolone)

In [27]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [28]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [29]:
A = np.array([1.0, 2.1, 3.3], dtype='int')
A.dtype

dtype('int64')

obcięte liczby z float do int

In [30]:
A

array([1, 2, 3])

In [31]:
A = np.array([True, False])
A.dtype

dtype('bool')

wbudowane typy np dla piksela - zajmują mniej miejsca int8

In [32]:
A = np.array([24, 12, 23], dtype=np.int8)
A.dtype

dtype('int8')

najlepiej wartości poksela od 0..255 uint8

In [33]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

### <a name='s3'></a> Tworzenie tablic

In [34]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.zeros(shape=(3, 2, 4, 10))

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0

In [38]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [44]:
np.arange(start=10, stop=100, step= 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
np.arange(start=100, stop=10, step= -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [46]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

równo rozłożony przedział od start do stop w liczbie=num elementami

In [47]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [48]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [49]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

reshape(3, -1) -> 3 wiersze i;e tam kolumn wyjdzie

In [55]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

reshape(-1, 3) -> 3 kolumny i ile tam wierszy wyjdzie

In [58]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])