<a href="https://colab.research.google.com/github/ArturPalys/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



*   @author: artur.palys@gmail.com
*   @site:



### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)

>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)

>Podstawowa biblioteka do obliczeń numerycznych w języku Python

```
pip install numpy
```

### Spis treści:


1.   [Podstawy](#s1)
2.   [Typy danych](#s2)




### <a name='s1'></a> Podstawy

In [2]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

wymiar tablicy

In [10]:
x.ndim

1

kształt - długość odpowiedniego wymiaru tablicy (tupla/krotka)


In [11]:
x.shape

(2,)

In [ ]:
help(np.shape)

In [14]:
x.size

2

typ danych

In [15]:
x.dtype

dtype('int64')

In [18]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [19]:
x.shape

(3,)

In [20]:
x.dtype

dtype('float64')

2D Array

In [5]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [6]:
x.ndim

2

In [7]:
x.shape

(2, 2)

In [9]:
x = np.array([[1, 2, 3], [4, 2, 1]])
x

array([[1, 2, 3],
       [4, 2, 1]])

2 wiersze 3 kolumny (2 wymiary-macierz)

In [11]:
x.shape

(2, 3)

3D Array (np obraz)

In [12]:
x = np.array(

             [[[4, 3, 2],
               [3, 1, 2]],

              [[4, 1, 3],
               [4, 2, 1]]]
)
x

array([[[4, 3, 2],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [13]:
x.ndim

3

2 tabele/elementy, 2 wiersze, 3 kolumny  (3 wymiary)

In [14]:
x.shape

(2, 2, 3)

### <a name='s2'></a>Typy danych

In [15]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [16]:
A = np.array([1.0, 2.1, 3.3])
A.dtype

dtype('float64')

In [17]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [18]:
A

array([1., 2., 3.])

liczby złożone (zespolone)

In [21]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [22]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [23]:
A = np.array([1.0, 2.1, 3.3], dtype='int')
A.dtype

dtype('int64')

obcięte liczby z float do int

In [24]:
A

array([1, 2, 3])

In [25]:
A = np.array([True, False])
A.dtype

dtype('bool')

wbudowane typy np dla piksela - zajmują mniej miejsca int8

In [31]:
A = np.array([24, 12, 23], dtype=np.int8)
A.dtype

dtype('int8')

najlepiej wartości poksela od 0..255 uint8

In [32]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')